### ISSUE TITLE
OleDb Driver

### ISSUE THREAD

**Issue by RickStrahl** [VFPX/VFP9SP2Hotfix3#2]
Could we also get the latest OleDb driver up here too? That way all the external bits are in one place.

Heck I would even go as far as also putting up a copy of Microsoft HTML Help Workshop  (in order to compile CHM files for FoxPro) since Microsoft has abandoned downloads for that.

**Comment by DougHennig** [comment]
I have a copy of the HTML Help Workshop installer so I'll add that. Do you have a copy of the latest OLE DB provider? I can't seem to find an installer for it.

**Comment by RickStrahl** [comment]
Done - added a pull request. There's no version number on the MSI but when I run it it says VFP 9 SP2 OleDb driver.
